var splashTexts = [
  "Léiert Formelen wei nach nie",
  "A spick a day keeps the Datz away.",
  "Datzen&shy;erhaltungs&shy;satz",
  "100% Bug fräih!",
  "tfarcenim",
  "html css javaScript json",
  "Knäipen ass ongesond",
  "Infoen zu Formelen aus Lëtzebuerg",
  "Play Games!",
  "formel.lu",
  "Iwwer 25 000 Linne Codage!",
  "Hurrah Formelen",
  "5 Stäre Bewertung",
  "COOKIES!!!!",
  "Datz oder keine Datz das ist hier die Frage",
  "Wiederhuelen wiederhuelen dat muss sinn!",
  "Wiederhuelen wiederhuelen sos kann dat näischt ginn!",
  "Q = m c delta theta",
  "Don't read me!",
  "Yvan Monka",
  "console.log&shy;(error);",
  "100% handmade",
  "Never Gonna Give You Up",
  "LateX",
  "Online säit dem 6.7.2022",
  "Apple Watch compatibel",
  "meng formelen? eis formelen!",
  "100% Spaghetti Code",
  "Science Technology Engineering Math",
  "Leben am Limit",
  "Print page, save as .pdf",
  "I'm in Mallorca",
  "formules en masse",
  "mario the mustache man",
  "Hausaufgaben mecht een an de Sproochen!",
  "Inspiréiert vum Dr. Marcel Schäffer",
  "an do geet de misär erem lass",
  "bravo bravo bravo",
  "rrrrrr&shy;rrrichteg!",
  "ass dat net schéin",
  "léieren ewéi déieren",
  "géi mol fënef minuten virun d'Dir",
  "Fraaaaanc&shy;ooooooo",
  "logisch?",
  "die bananen statue",
  "dommheets&shy;konstante",
  "what an amazing day",
  "kommando! umdrehen!",
  "wahrnschuss!",
  "How to make a milkshake",
  "very colourful",
  "médiatrice bissectrice",
  "cosinusoid",
  "hacovercosin",
  "Bonjoo&shy;ouuuuuur",
  "guer net seriö dat doten!",
  "124 Kapitelen",
  "1,41 GB",
  "we do not brew coffee - Error : 418",
  "server is a teapot",
  "please convert me",
  "help me I'm trapped code!",
  "NOMAD",
  "sehr große Messfehler",
  "Hola",
  "¿Qué tal?",
  "Olà",
  "Oi",
  "Moien",
  "Salut",
  "Pozdrav",
  "Good Morning",
  "Gudde Moien",
  "N'Owend",
  "Ciao",
  "Salve",
  "Konnichiwa",
  "Anyoung haseyo",
  "Anyoung",
  "Asalaam alaikum",
  "Ahlan",
  "Goddag",
  "Halløj",
  "Shikamoo",
  "Hoi",
  "Yassas",
  "Yassou",
  "Witaj",
  "Selamat siang",
  "Halo",
  "Namaste",
  "Shalom",
  "Hey",
  "God dag",
  "Tjena",
  "Buona sera",
  "The Power of Now",
  "Things to make and do in the 4th dimension",
  "May contain Mathematics",
  "As seen on TV",
  "Physics everywhere",
  "Ceci n'est pas une title screen!",
  "sqrt(-1) love you!",
  "Un croissant fourré svp",
  "treatment for your Datz",
  "Bread is pain!",
  "luxformel.info presents : useless formulas!",
  "[redacted] our lord and saviour",
  "eng laang équatioun hues du do",
  "check the change log",
  "don't go chasing datzen",
  "formula heaven",
  "Prinzessin der neuen Flut",
  "señior Gartenstuhl",
  "welcome back chief",
  "hog ridaaaaa",
  "the bee's knees!",
  "Oh-ooh-whoa&shy;-oh-oh-oh-oh",
  "It's a party in the luxformel.info",
  "comment jouer à la pétanque?",
  "el jarabe tapatío",
  "cactus compactus",
  "[error: could not generate Text]",
  "Aluminium&shy;fluoridium",
  "Coucou c'est moi",
  "tu dis:«jo jo jo» moi je dis:«nee!»",
  "Someone improved my code by 40,832,&shy;277,770%",
  "Orangutangu",
  "a website of unnecessary detail",
  "Luxus Formelen",
  "Heather the unicorn",
  "www.maths-et-tiques.fr",
  "motivation is a lie",
  "lod.lu",
  "zls.lu",
  "llo.lu",
  "verben.lu",
  "schreifmaschinn.lu",
  "spellchecker.lu",
  "Léiwe Kleeschen",
  "Gudde Kleeschen",
  "Last christmas",
  "Now On Air!",
  "check the READ ME",
  "footlose",
  "This is a robbery!",
  "André came from Speckistan!",
  "Dark mode",
  "undergoing upgrades to the core infra&shy;structure of the ecosystem",
  "synergy",
  "oranje!",
  "Hosted in Holland",
  "I am the hackerman&shy;!1!!!",
  "VAPOR WAVE!!!",
  "User-agent: *  <br> Disallow: /",
  "robots.txt",
  "Skorpioun",
  "Progressive Web Application",
  "Install me!",
  "php - free!",
  "personal home page",
  "HyperText Markup Language",
  "Cascading Stylesheets",
  "dynamically typed!",
  "manifest.json",
  "you won a million formulae claim now!",
  "jemangede&shy;laire.fr",
  "Splash Screen Text!",
  "Jëses Kanner!",
  "Eifeler Reegel",
  "Voyage, voyage",
  "C418",
  "Let's play boolean",
  "fly me out of the school",
  "weak Argumenter!",
  "oh nee ërem eng datz",
  "just in time compiled",
  "herrlech",
  "fooschen",
  "radetten",
  "ëmäerbelen",
  "elo huet dee Blëll d'Dier zougezunn",
  "Intebinnessen",
  "Moie Rollefax!",
  "O Mei O Mei",
  "nondijö nach mol",
  "fuschnei an nach ëmmer net an der Rei",
  "gare la Box, du sees mer net d'Wouerecht!",
  "gare la Minn, du sees mer net d'Wouerecht!",
  "Maach der eng Check-List",
  "Hei elei, kuck elei",
  "Intolerance will not be tolerated",
  "Thanks, Anonymous!",
  "send me an email",
  "send me an angel",
  "promises, promises",
  "Ee Formelheft mä Online!",
  "git commit innit?",
  "join us on github",
  "Oh So Magnanimous!",
  "Going to 5D!",
  "Rip Mix Burn",
  "Wir kommen in frieden!",
  "https://filedn.eu/&shy;lR5G6WKEMs8uYdor&shy;VcyFS6V/index.html",
  "Jirrimirri!",
  "DE BUTTEK FÄNKT U MAT DRÉIEN!",
  "Chrom net Krom!",
  "Sir Kamelott",
  "sudo apt-get update",
  "sudo apt-get upgrade",
  "Aria Math",
  "Biome Forest",
  "Java != JavaScript",
  "Bug fixes and improvements",
  "Formula Museum",
  "Learn to Code",
  "self development!",
  "Booyakasha!",
  "Boom Boom check the mofo room!",
  "very nice, i like!",
  "static site?",
  "Bird up!",
  "We'll Be Right Back!",
  "Why did I move here? I Guess it was the weather.",
  "Thinking fast and slow.",
  "Hello guys I'm under the water",
  "Campus Kirchberg",
  "Campus Belval",
  "we only eat cookies",
  "Solve some quadratic equations",
  "Une solution réelle double",
  "Luxformel: the home of spaghetti code",
  "Let's solve 2000 equations",
  "3000 iq human",
  "Luxformel Pro Max Ultra",
  "Computator",
  "Hey...",
  "Pls be a challenge",
  "Greetings carbon based life form",
  "... it describes a singular form",
  "You know the rules and so do I",
  "Code written with the help of pink elephants",
  "Prof. Dr. Dr. habil. rer. nat. Numm Familjennumm",
  "Oh nee ech hunn den Donald Tram verpasst!!!",
  "Abstract Factory Manager Singelton Service Manager Factory",
  "Ecmascript???",
  "Document object model",
  "Domain name system",
  "Uniform resource locator",
  "Hypertext transfer protocol",
  "Transmission control protocol",
  "Internet protocol",
  "common gateway interface",
  "Generative pre-trained transformers",
  "Large Language Model",
  "pre-trained transformer",
  "Reinforcement learning from human feedback",
  "Machine Learning",
  "dimensionality reduction",
  "service worker",
  "Welcome to the turing machine",
  "Chefs kiss",
  "Inspiration Innovation Celebration",
  "Ceci n'est pas un luxformel",
  "Ceci n'est pas un site",
  "Plain and simple",
  "Industrial design",
  "Luxformel-gpt",
  "Looky looky cookie",
  "Don't discriminate the discriminate",
  "si et seulement si",
  "Jede einfach zusammenhängende, kompakte, unberandete, 3-dimensionale Mannigfaltigkeit ist homöomorph zur 3-Sphere",
  "Mathewelten",
  "Voyage au pays des maths",
  "Das topologische Lasso",
  "Banach Spaces",
  "kebab-case",
  "PascalCase",
  "snake_case",
  "camelCase",
  "lucilinburhuc",
  "viisaus?",
  "newtonian lagrangian hamiltonian",
  "Pizza Aquisition",
  "Ich beisse den Hund!",
  "Die Tafel spielt Klavier.",
  "Do you have issues?!",
  "Wat der Jomer!",
  "vu Pontius op Pilatus",
  "vun Hippches op Hapches",
  "Life is better with the unit cricle",
  "Totally legitmate businessman",
  "Un vrai virtuoso",
  "Birds aren't real",
  "GLOME",
  "rest in spaghetti never forgetti",
  "blackpen&shy;redpen",
  "don't worry, I have the solution",
  "Do as I say, not as I do.",
  "comb it with a brick",
  "boop",
  "The alpha fish",
  "14 pages!!!!",
  "wasted",
  "heyoooo",
  "You've gone incognito",
  "All you can eat",
  "Kernkraft 400",
  "Intelligence artificielle ou stupidité naturelle?",
  "The science of successful learning",
  "make it stick!",
  "Epsilon delta",
  "Luxformel Luxéquation Luxthéorème",
  "Luxformel: Een eenzegen Zimlabum!",
  "Nemme Fisematenten...",
  "Baruch Spinoza",
  "boumm équatioun, boumm dérivée",
  "Wei léiert ee scho méi?",
  "One small step for a man, one giant leap for mankind",
  "No privacy Zuckering, pls?",
  "Welcome to roach motel...",
  "No dark patterns!",
  "Sub specie aeternitatis",
  "Sub specie durationis",
  "reflection, practice, spacing",
  "The school of life",
  "Egg nog",
  "Please no slides",
  "Once upon a time in a clearing in a magical forest...",
  "Klimmbimm Entusiast",
  "Life is contrary",
  "Faal op eng Millioun!",
  "The finals",
  "In varietate concordia",
  "Let the man cook!",
  "Il faut écouter le docteur",
  "There is nothing we can do",
  "Better call Ahmad",
  "Back when the air was still invisible an toothpaste was still white",
  "User? Do you know why you're here?",
  "Bad luck I guess",
  "Sischer, Siscer, Herr Makielski!",
  "Ey Mann, isch werd' bekloppt, ey!",
  "Alles für den Dackel, alles für den Club. Unser Leben für den Hund!",
  "Wissen macht AH! Aaaa&shy;aaaHHHHHHHHH",
  "No clubbing, stepping, flinching",
  "De Jang vun Detroit",
  "Wat ee Steemetz Decolleté!",
  "This is seven Dollars!?",
  "Entspannen ist ein Vollzeitjob",
  "Le monde est fou, croyez nous!",
  "Moodle Jump",
  "Crisis averted",
  "Ich bin für regulierung, nicht für strangulierung",
  "Can't Pay Take It Away!",
  "Eigelb enthält mehr Eiweiß als Eiweiß",
  "De Sproochmates",
  "Hasta la vista, Baby!",
  "De Kropemann...",
  "D'Klierf zu Clierf!",
  "Luxemburgistik",
  "Zënter éiweg an dräi Deeg",
  "Kalsarikännit",
  "Physik: fisike, physica, physikḗ, physikós",
  "Die Jagd beginnt!",
  "Der Quizgott und Quizvulkan",
  "// some code here",
  "Food for Bomm",
  " < !DOCTYPE html > ",
  "public static void main(String[] args){ <br> }",
  "var body: some View{ <br> }",
  "I believe in Mirko",
  "J'ai eu la chance de ne pas le connaître",
  "La synthèse des opposés",
  "generate&shy;RandomText();",
  "Ethos, Pathos, Logos",
  "I don't like smalltalk, I prefer largetalk",
  "D'Sich nom Fong!",
  "Mam Fong geet am Fong alles!",
  "Glep",
  "Hier kommt der Jäger!",
  "Ce n'est pas possible que les oignons soient des zwiebels!",
  "What is the probability I appeared?",
  "Mathematik + Information = Informatik?",
  "Who is Goonch??",
  "lüxförmel",
  "Let's do it S.M.A.R.T.",
  "A lot of code has been written!",
  "De Bauzi fir den et Staatstrauer gëtt!",
  "Nei Spréch!",
  "We think you are going to like it",
  "Animus in consulendo liber",
  "J'ai du déjà vu... je pense...",
  "Content de te revoir",
  "Luxformel: A conserver à l'abri du soleil dans un endroit sec et frais",
  "MVVM? MVC?",
  "importing Formulas...",
  "Aufgehts, Abgehts!",
  "Did you ever mean it?",
  "Dérivéeë Rechnen! An zwar 3814!",
  "Bienvenue dans l'habitat naturel des formules",
  "Welcome to the natural habitat of formulas",
  "Wëllkomm am natierleche Liewensraum vun de Formelen",
  "Never show anyone your luformelID, it's too secret!",
  "SplashScreenText splashscreenText = new SplashScreenText();",
  "More polygons!",
  "As seen on TV!",
  "Made in ????",
  "This message will never appear on the splash screen, isn't that weird?",
  "Homeomorphic to a 3-sphere!",
  "luxformel.party();",
  "/give @a formula 64",
  "From free range developers!",
  "Information wants to be free!",
  "Scary!",
  "Chickens: clucking and plotting world domination. <br> - LLM",
  "A significantly smaller language model than expected...",
  ":)",
  ":=)",
  "\\_(*_*)_/",
  ":-D ",
  ":-P ",
  ";-)",
  ":-O ",
  ":-|",
  ":-/",
  ":-* ",
  ":-X",
  ":-$",
  ":-S",
  ":-!",
  ":'-(",
  ":-@",
  ":-]",
  ":-[",
  ":-}",
  ":-&",
  ":-\\",
  ":=>",
  ":')",
  "\\_(-.-)_/",
  "(^_^)",
  "_(>.<)_",
  "_(o_o)_",
  "_(.)_",
  "_(0.0)_",
  "_(^.^)_",
  "_(-_-)_",
  "_(=_=)_",
  "N'Ja",
  "Is: 8 = D?",
  "0_o <br> I'm sorry I wasn't expecting you!",
  "＿＿ <br> │〓.│ <br> ━━━━━ <br> ﾐ　´_＞｀）",
  "En Dill do an een Dill do!",
  "Der April macht was er will",
  "you spin my head right 'round...",
  "Welcome to your life, <br> There's no turning back,",
  "Commit yourself? <br> It's my life!",
  "Freed from desire, mind and sense are purified",
  "I can't wait <br> for the weekend to begin",
  "Get, get, get, get, got, got, got, got,",
  "Convergence!",
  "U-Void Syntheziser",
  "Bass d'Essenz vum Liewen!",
  "digital hardcore",
  "Tri o let",
  "ta ti ti tiri tiri ta",
  "Devil Speak",
  "Formation musicale ou formation musicale?",
  "what is this knocking sound from the edge of the world?",
  "Eng hellewull u Formelen!",
  "Konscht!",
  "6 Silhouetten...",
  "Dogs playing Poker <br>- C.M. Coolidge",
  "Skrik <br>- Edward Munch",
  "De sterrennacht <br>- Vincent van Gogh",
  "Nighthawks <br>- Edward Hopper",
  "Farbstudie: Quadrate mit konzentrischen Ringen <br>- Wassily Kandinsky",
  "Les Demoiselles d'Avignon <br>- Pablo Picasso",
  "La Liberté guidant le peuple <br>- Eugène Delacroix",
  "Blue and Green Music <br>- Georgia O'Keeffe",
  "Golconde <br>- René Margritte",
  "Girl with Balloon <br>- Banksy",
  "Pool with Two Figures <br>- David Hockney",
  "101 = 5?",
  "Protect Nature!",
  "We are å®@∂®†ßªªªß®ß∂",
  "Aus jux, Formel!",
  "Uncommited changes...",
  "augmented irreality",
  "Tomber dans les pommes",
  "Terassenassel",
  "LËTZEBUERGER LINGUISTIK A LITERATUR",
  "La nature est indifférente!",
  "Pauk mit Latein",
  "Tässel dee Stoffi net esou op d'Schmier",
  "Et schëdd wei mat Eemeren",
  "Dyslexiker Frëndlech!",
  "Lieber Heute, statt Morgen!",
  "Deen huet eng Klatz wei eng Rommel",
  "zackerdjëss!!!!!",
  "Kräizdonnerwieder&shy;!!!!!!!",
  "Eddy will read it to you!",
  "Software that helps us write other software!",
  "Garbage in, garbage out",
  "special JavaFX!",
  "Text to speech",
  "Guud'n Aamd",
  "tabula rasa!",
  "Don't be radicalised",
  "Stay calm!",
  "Believe in no anger",
  "Groussen Auto Déifstall",
  "D'Alien si convoquéiert!",
  "Roude Léiw huel se",
  "Lëtz make it happpen",
  "Da brennt noch Licht aber es ist niemand zuhause",
  "Da hilft auch alles klingeln nichts",
  "Eisen Noper huet a sengem Bongert Mirabellebeem geplanzt",
  "SPEED TRAM SPEED!!!!",
  "All the way with tramway!",
  "Seid Ihr alle da?",
  "I'm emitting the heat!",
  "Huele mer de Siggy?",
  "Expanded and Enhaced",
  "We did the maths, we did the calculations",
  "I'll be back",
  "BING! BANG!!! BOOOOOOMMMMMM!!!!!!",
  "Do you have asbestos hands?",
  "We visited the green light district",
  "and we're all out of gas!",
  "You are the best!",
  "I'm not a robot",
  "Luxformel Intelligence",
  "Someone is watching us!",
  "Some kind of nature",
  "It's coming up! <br> It's dare!",
  "Chef Luxformel",
  "quack quack",
  "Where is the lamb sauce?",
  "glhf",
  "Jullienne, Chiffonade, Burnoise, Batonnet???",
  "oh, that's a nice hat",
  "A series of tubes",
  "glub glub",
  "And it goes like this...",
  "My formulas bring all the boys to the yard <br> and they're like it's better than yours",
  "Let's have some fun this eqution is sick <br> I wanna take a ride on you sinus wave",
  "I like to solve it, solve it",
  "Il m'entaînent au bout de la nuit les demons de minuit",
  "I ain't happy, I'm feeling glad <br> I got sunshine in a bag",
  "City's breakin' down on a camels back",
  "I say don't you know <br> You say you don't know <br> I say take me out",
  "Let's get it started in (Ha) <br> Let's get it started (In here)",
  "And runnin' runnin' <br> And runnin' runnin'<br> And runnin' runnin'<br> And runnin' runnin'",
  "Come on now, who do you <br>who do you, who do you, who do you think you are?",
  "You really think you're in control?",
  "It's gone daddy gone <br> The love is gone",
  "I crashed my car into a bridge <br> I don't care <br> I love it",
  "Who really is the GOAT?",
  "Luxformel: written with help from machine learning",
  "Designed for bio chemical beings",
  "We at luxformel, we love water",
  "How do I center a div?",
  "Uploading downdate...",
  "1/565",
];
function generateRandomText() {
  //console.log(splashTexts);
  var randomNumber = Math.floor(Math.random() * splashTexts.length);
  //var randomNumber = 560;
  //console.log(randomNumber);
  //console.log(splashTexts[randomNumber]);
  document.querySelector("#sst").innerHTML = splashTexts[randomNumber];
}
generateRandomText();
