var splashTexts = [
  "A spick a day keeps the Datz away.",
  "Datzen&shy;erhaltungs&shy;satz",
  "100% Bug fräih!",
  "tfarcenim",
  "html css javaScript json",
  "Knäipen ass ongesond",
  "Infoen zu Formelen aus Lëtzebuerg",
  "Play Games!",
  "formel.lu",
  "Iwwer 20 000 Linne Codage!",
  "Hurrah Formelen",
  "5 Stäre Bewertung",
  "COOKIES!!!!",
  "Datz oder keine Datz das ist hier die Frage",
  "Wiederhuelen wiederhuelen dat muss sinn!",
  "Wiederhuelen wiederhuelen sos kann dat näischt ginn!",
  "Q = m c delta theta",
  "Don't read me!",
  "Yvan Monka",
  "console.log&shy;(error);",
  "100% handmade",
  "Never Gonna Give You Up",
  "LateX",
  "Online säit dem 6.7.2022",
  "Apple Watch compatibel",
  "meng formelen? eis formelen!",
  "100% Spaghetti Code",
  "Science Technology Engineering Math",
  "Leben am Limit",
  "Print page, save as .pdf",
  "I'm in Mallorca",
  "formules en masse",
  "mario the mustache man",
  "Hausaufgaben mecht een an de Sproochen!",
  "Inspiréiert vum Dr. Marcel Schäffer",
  "an do geet de misär erem lass",
  "bravo bravo bravo",
  "rrrrrr&shy;rrrichteg!",
  "ass dat net schéin",
  "léieren ewéi déieren",
  "géi mol fënef minuten virun d'Dir",
  "Fraaaaanc&shy;ooooooo",
  "logisch?",
  "die bananen statue",
  "dommheets&shy;konstante",
  "what an amazing day",
  "kommando! umdrehen!",
  "wahrnschuss!",
  "How to make a milkshake",
  "very colourful",
  "médiatrice bissectrice",
  "cosinusoid",
  "hacovercosin",
  "Bonjoo&shy;ouuuuuur",
  "guer net seriö dat doten!",
  "85 Kapitelen",
  "112.5 MB",
  "we do not brew coffee - Error : 418",
  "server is a teapot",
  "please convert me",
  "help me I'm trapped code!",
  "NOMAD",
  "sehr große Messfehler",
  "Hola",
  "Ciao",
  "Olà",
  "Moien",
  "Salut",
  "Pozdrav",
  "Good Morning",
  "The Power of Now",
  "Things to make and do in the 4th dimension",
  "May contain Mathematics",
  "As seen on TV",
  "Physics everywhere",
  "Ceci n'est pas une title screen!",
  "sqrt(-1) love you!",
  "Un croissant fourré svp",
  "treatment for your Datz",
  "Bread is pain!",
  "luxformel.info presents : useless formulas!",
  "[redacted] our lord and saviour",
  "eng laang équatioun hues du do",
  "check the change log",
  "don't go chasing datzen",
  "formula heaven",
  "Prinzessin der neuen Flut",
  "señior Gartenstuhl",
  "welcome back chief",
  "hog ridaaaaa",
  "the bee's knees!",
  "Oh-ooh-whoa&shy;-oh-oh-oh-oh",
  "It's a party in the luxformel.info",
  "comment jouer à la pétanque?",
  "el jarabe tapatío",
  "cactus compactus",
  "[error: could not generate Text]",
  "Aluminium&shy;fluoridium",
  "Coucou c'est moi",
  "tu dis:«jo jo jo» moi je dis:«nee!»",
  "Someone improved my code by 40,832,&shy;277,770%",
  "Orangutangu",
  "a website of unnecessary detail",
  "Luxus Formelen",
  "Heather the unicorn",
  "www.maths-et-tiques.fr",
  "motivation is a lie",
  "lod.lu",
  "verben.lu",
  "Léiwe Kleeschen",
  "Gudde Kleeschen",
  "Last christmas",
  "Now On Air!",
  "check the READ ME",
  "footlose",
  "This is a robbery!",
  "André came from Speckistan!",
  "Dark mode",
  "undergoing upgrades to the core infra&shy;structure of the ecosystem",
  "synergy",
  "oranje!",
  "Hosted in Holland",
  "I am the hackerman&shy;!1!!!",
  "VAPOR WAVE!!!",
  "User-agent: *  <br> Disallow: /",
  "robots.txt",
  "Skorpioun",
  "Progressive Web Application",
  "Install me!",
  "php - free!",
  "personal home page",
  "HyperText Markup Language",
  "Cascading Stylesheets",
  "dynamically typed!",
  "manifest.json",
  "you won a million formulae claim now!",
  "jemangede&shy;laire.fr",
  "Splash Screen Text!",
  "Jëses Kanner!",
  "Eifeler Reegel",
  "Voyage, voyage",
  "C418",
  "Let's play boolean",
  "fly me out of the school",
  "weak Argumenter!",
  "oh nee ërem eng datz",
  "just in time compiled",
  "herrlech",
  "fooschen",
  "radetten",
  "ëmäerbelen",
  "elo huet dee Blëll d'Dier zougezunn",
  "Intebinnessen",
  "Moie Rollefax!",
  "O Mei O Mei",
  "nondijö nach mol",
  "fuschnei an nach ëmmer net an der Rei",
  "gare la Box, du sees mer net d'Wouerecht!",
  "gare la Minn, du sees mer net d'Wouerecht!",
  "Maach der eng Check-List",
  "Hei elei, kuck elei",
  "Intolerance will not be tolerated",
  "Thanks, Anonymous!",
  "send me an email",
  "send me an angel",
  "promises, promises",
  "Ee Formelheft mä Online!",
  "git commit innit?",
  "join us on github",
  "Oh So Magnanimous!",
  "1/170",
];
function generateRandomText() {
  //console.log(splashTexts);
  var randomNumber = Math.floor(Math.random() * splashTexts.length);
  // var randomNumber = 124;
  //console.log(randomNumber);
  //console.log(splashTexts[randomNumber]);
  document.querySelector("#sst").innerHTML = splashTexts[randomNumber];
}
generateRandomText();
